Project-1: Initialisation
SamanAtashi/BookStore pull request #1
Opened 2021-09-09 07:20 UTC by SamanAtashi

# Project 1 : Initialisation
Features introduced are as follows:
1. React-Redux
2. ducks pattern
3. React Router

2021-09-09 09:41 UTC, dasileker requested changes
### **Hi @SamanAtashi** 

Good job so far!
You are almost there, you need just a little and fix some issues that are required to change 🔴

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-09 09:41 UTC, dasileker commented on src/components/Categories.jsx
> +export default Categories;
- [ ] This component should be  done as `Route or Link` see the screenshot 👇.

![kklkl](https://user-images.githubusercontent.com/61562626/132661779-c695d6db-72bf-4151-ab7c-b3ce1f5b6730.jpeg)

2021-09-09 09:41 UTC, dasileker commented on src/components/Books.jsx
> +);
- [ ] also This should be the same as the category `Routes or Link`

2021-09-09 09:41 UTC, dasileker commented on src/components/Book.jsx
> +  ));
- [ ] This function should have a propTypes and  validate it.

![lmlml](https://user-images.githubusercontent.com/61562626/132662373-eff2f57b-6fb8-4f0e-84ca-30f9980cccd6.jpeg)

2021-09-10 05:14 UTC, oxenprogrammer approved these changes
Hi **@SamanAtashi** , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-10 05:16 UTC, merged