Project 3: api
SamanAtashi/BookStore pull request #3
Opened 2021-09-10 16:31 UTC by SamanAtashi

# Project 3: API
Features introduced are as follows:
- connect API to react/redux app

2021-09-10 18:14 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @SamanAtashi 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
 - The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
-  Git/GitHub flow best practices have been followed.:heavy_check_mark:
- Data are being sent and received from API:heavy_check_mark:

Changes required :writing_hand: 
 
    - Please check the comment under the review.

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-10 18:14 UTC, Emmyn5600 commented on src/components/Books/Book/AddBook.jsx
>  import React from 'react';
- [x] Fix eslint errors without disabling the line of code

2021-09-10 18:14 UTC, Emmyn5600 commented on src/components/Books/Book/Book.jsx
>  import { useSelector, useDispatch } from 'react-redux';
- [ ] Fix eslint errors without disabling the line of code

2021-09-10 18:14 UTC, Emmyn5600 commented on src/components/Books/Book/Book.jsx
> +
- [x] Let us validate our add button to prevent us to adding the empty data
![cpp13](https://user-images.githubusercontent.com/55635977/132898757-2125baea-8501-44f5-a9f8-0d27952f8a96.png)

2021-09-11 05:09 UTC, oxenprogrammer approved these changes
Hi **@SamanAtashi** , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-11 05:09 UTC, oxenprogrammer commented on src/API/api_connect.js
> +  console.log('sended to api');
**Optional Changes**
The previous Code Reviewer missed it, however;
- [ ] You shouldn't commit `console.log` to production. It makes your code look messy (code smell). 
Let us try to remove all the occurrences of `console.log` before merging.

2021-09-11 05:09 UTC, oxenprogrammer commented on src/components/Books/Book/AddBook.jsx
> +      alert('Please fill both inputs!!!');
**Optional Changes**
The previous Code Reviewer missed it, however;
- [ ] Let us restrain from using `windows.alert` . Simply put, it is difficult to test. 
Let us try to remove it before merging.

2021-09-11 05:25 UTC, merged